version: "3.9"
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    networks:
      - backend

networks:
  backend:
    driver: bridge
